Third feature
sj1978/school-library-ruby pull request #3
Opened 2022-02-02 21:23 UTC by sj1978

In this feature I :  
Created Classroom, Books and Rentals classes
Added all the requested relationships and attributes.
Checked linters

2022-02-02 21:39 UTC, mikethreels requested changes
Hi Anibal, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-02 21:39 UTC, mikethreels commented on classroom.rb
> +  end
- [ ] in order to make this work you will need to set up the attribute reader for `@students` as well

2022-02-02 21:39 UTC, mikethreels commented on student.rb
> +end
- [ ] in order to make this work you will need to set up the 'belongs-to' side as well as mentioned in [this article](https://github.com/microverseinc/curriculum-ruby/blob/main/oop/articles/oop_relationships_by_examples.md#both-ways-relationships).

2022-02-02 21:39 UTC, mikethreels commented on book.rb
> +  end
- [ ] in order to make this work you will need to initialize the rental class in this method as explained in [this article](`https://github.com/microverseinc/curriculum-ruby/blob/main/oop/articles/oop_relationships_by_examples.md#many-to-many-relationship`).

2022-02-02 21:39 UTC, mikethreels commented on rental.rb
> +  end
- [ ] you're going to need to initialize the `book` and `person` as well in this method which will take both as arguments. and the rental should add itself to the instance variable created, which will look something like below:
```
    @book = book
    book.rentals << self

    @person = person
    person.rentals << self
```

2022-02-02 21:39 UTC, mikethreels commented on person.rb
> +  end
- [ ] in order to make this work you will need to initialize the rental class in this method as explained in [this article](`https://github.com/microverseinc/curriculum-ruby/blob/main/oop/articles/oop_relationships_by_examples.md#many-to-many-relationship`).

2022-02-02 22:52 UTC, mikethreels requested changes
Hi Anibal, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-02 22:52 UTC, mikethreels commented on student.rb
> +  end
- [ ] what I meant with the previous review is that there needs to be a method which looks like the below example:
```
def classroom=(classroom)
      @classroom = classroom
      classroom.students.push(self) unless classroom.students.include?(self)
  end

```

2022-02-02 22:52 UTC, mikethreels commented on book.rb
> +    rental.book = self
- [ ] with the previous comment I meant that the rental class should be initialized similarly to below:
```
  def add_rental(person, date)
    Rental.new(date, self, person)
  end
```

2022-02-02 22:52 UTC, mikethreels commented on person.rb
> +    rental.person = self
- [ ] with the previous comment I meant that the rental class should be initialized similarly to below:
```
 def add_rental(book, date)
    Rental.new(date, book, self)
  end
```

2022-02-03 03:22 UTC, omar-labana commented
Hi @sj1978, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-03 03:32 UTC, merged